### ISSUE TITLE
Add support for storybook 7

### ISSUE THREAD

**Issue by amurf** [storybookjs/testing-vue3#10]
No `next` version seems to have been created for this library, which breaks our whole test suite when attempting to upgrade to storybook 7

I've had a look at the issue a little bit, and after updating `addons` to use a named export (#9) there is a bunch of typing changes that I can't quite figure out.

This has been done for the react equivalent repo already here https://github.com/storybookjs/testing-react/pull/120 and a lot of it would be re-usable here as far as I can tell

**Comment by EwenDC** [comment]
This package, as well as `@storybook/testing-vue` and `@storybook/testing-angular`, are currently recommended in the Storybook v7 docs despite none of them working with v7! We need some clear communication on if you plan to maintain these addons at all, as the fact that `@storybook/testing-react` got ported and integrated into the core API is sending mixed messages.
![image](https://user-images.githubusercontent.com/39972488/229713165-3c3b5a4f-96c3-4434-8614-94acb676553c.png)

**Comment by MichaelBitard** [comment]
Is there something we can do to help @yannbf?
Sorry to ping you but it seems you are (were?) the main committer on the repo

**Comment by yannbf** [comment]
Hey everyone! Thanks for raising this issue. Things are quite busy at the moment which makes it tough to update all of these packages, sorry about that!

I’d really love some help if anyone is up for it. the `@storybook/testing-react` lib has been updated and you could use it as a reference to get this library to a similar state. You can check the differences in [this file](https://github.com/storybookjs/testing-react/blob/future/src/index.ts) and bring them to [this file](https://github.com/storybookjs/testing-vue3/blob/main/src/index.ts) in this library. I’m happy to assist along the way and help get this to the finish line!

We also are going to update the documentation to reflect the current state of these packages.

Thank you so much!

**Comment by yannbf** [comment]
Hey there, this is now supported in version 1.0.0 of this package. Thank you so much for your patience <3
