### ISSUE TITLE
Using Play inside test files

### ISSUE THREAD

**Issue by fazulk** [storybookjs/testing-vue3#3]
I noticed there isn't an option to run interactions from within a test file with the `Play` method. I have it running on a forked branch, but can't get it to actually execute userEvents. Is there any proposed update with this feature on the roadmap? I noticed it on the React version.

**Comment by fazulk** [comment]
see #4

**Comment by MichaelBitard** [comment]
@fazulk is there a way to do that? Your PR #4 has not been merged

**Comment by yannbf** [comment]
Hey there, this is now supported in version 1.0.0 of this package. Keep in mind that it requires Storybook 7.0.0!
