### ISSUE TITLE
[Bug] Issue with composeStories when used with Vitest in Storybook 7

### ISSUE THREAD

**Issue by K3TH3R** [storybookjs/testing-vue3#9]
### Describe the bug

I've been starting to migrate our Vite/Vue 3 repo over to Storybook 7 and I'm running into a weird error as soon as I import `composeStories` into a test file.

Simply by adding the following lines:
```ts
import * as stories from './BasicButton.stories.js'
import { composeStories } from '@storybook/testing-vue3'
const composed = composeStories(stories)
```

I get the following error:
```shell
 FAIL  src/components/BasicButton/BasicButton.spec.ts [ src/components/BasicButton/BasicButton.spec.ts ]
TypeError: addons__default.setChannel is not a function
 ❯ Object.<anonymous> node_modules/@storybook/testing-vue3/src/index.ts:11:8
 ❯ Object.<anonymous> node_modules/@storybook/testing-vue3/dist/index.js:7:20
```

Which seems to be happening [here](https://github.com/storybookjs/testing-vue3/blob/main/src/index.ts#L11). I have `@storybook/addons` installed, but I assume it might be expecting an instance of Storybook that wouldn't be running when we're doing unit tests outside of Storybook?

### Steps to reproduce the behavior

1. I've created a sample repo here: https://github.com/K3TH3R/composeStories-issue-storybook-7
2. If you clone/install and then run `yarn test:unit`, you should see the error.
3. If you comment out [this line](https://github.com/K3TH3R/composeStories-issue-storybook-7/blob/main/src/components/BasicButton/BasicButton.spec.ts#L3) you should see the test finish as expected.

### Expected behavior

I would expect to be able to run this properly. This exact setup is working as expected when we're on Storybook v6.

### Environment

 - OS: Mac OS
 - Node.js version: 16.19.0
 - NPM version: 8.19.3

**Comment by yannbf** [comment]
Hey there, this was fixed in v0.0.2, please try it out and reopen the issue if it didn't work. Thank you!
